import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import json
import shutil
import scipy.optimize as so
import scipy.constants as sc
import kremboxer.utils.greybody_utils as gbu
import datetime


def compute_fiveband_calibration(cal_params: dict):
    """
    Computes model for retrieving radiance measurements from voltage readings generated by longwave, midwave, wide
    3.95, and 10.95um sensors on the fiveband devices

    Parameters
    ----------
    cal_params: dict
        "calibration_inputs_folder": folder containing the below calibration input data
        "LW_bandpass": bandpass for the longwave sensor, path to csv
        "MW_bandpass": bandpass for the midwave sensor, path to csv
        "WIDE_bandpass": bandpass for the wideband sensor, path to csv
        "3.95_bandpass": bandpass for the narrow 3.95um sensor, path to csv
        "10.95_bandpass": bandpass for the narrow 10.95um sensor, path to csv
        "cal_input": sensor values collected with a blackbody for calibration, path to csv
        "temp_cal_input": lookup table relating temperature to resistance of the temperature sensor inside the device, path to csv
        "v_top": voltage applied across the internal temperature sensor voltage divider
        "r_top": resistance of resistor in internal temperature sensor voltage divider
        "calibration_outputs_folder": folder to store the calibration results

    Returns
    -------
        None, calibration results are saved to file
    """